[project]
name = 'regenerative-carbon-farming-marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.regenerative-farming-incentivizer]
path = 'contracts/regenerative-farming-incentivizer.clar'
clarity_version = 3
epoch = 3.1

[contracts.soil-carbon-measurement-system]
path = 'contracts/soil-carbon-measurement-system.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
